# Generated by Django 4.0.1 on 2022-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='password',
            field=models.CharField(default=4545, max_length=20),
            preserve_default=False,
        ),
    ]
