# Generated by Django 4.0.1 on 2022-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_info_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Email',
            field=models.EmailField(default=4545, max_length=240),
            preserve_default=False,
        ),
    ]
