# Generated by Django 4.0.1 on 2022-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='intak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intakname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trackname', models.CharField(max_length=20)),
            ],
        ),
    ]
